### ISSUE TITLE
Is this using the bag of words technique?

### ISSUE THREAD

**Issue by shreya-singh-tech** [Parassharmaa/Tweet-Classifier#1]
for word in word_features:
		features['contains(%s)' % str(word)] = (word in document_words)
	return features

is this using the tf-idf format?

**Comment by Parassharmaa** [comment]
Yes, it is bag of words, but not using tf-idf. 

I would appreciate a contribution in that case.

**Comment by shreya-singh-tech** [comment]
so basically you are checking for frequency of words in each document?

could you explain how your are taking in the features?

**Comment by Parassharmaa** [comment]
This is just simple bag of words.

This is how it is working.

Lets take 2 sentences:
* I like winters not summers.
* He likes winters and summers.

Vector Representation:

all_words = ['i', 'like', 'winters', 'he', 'and', 'not', 'summers'] 
``` python
[{
    'i': true,
     'like': true,
     'winters': true,
     'he': false,
     'and': false,
     'not': true,
     'summers': true
 },
 {
    'i': false,
     'like': true,
     'winters': true,
     'he': true,
     'and': true,
     'not': false,
     'summers': true
 }]
```
In other way it can also be represented as:
``` python
[  
    [1, 0, 1, 0, 0, 1, 1],
    [0, 1, 1, 1, 1, 0, 1]
]
```

Here I am just checking that whether a given sentence contains a particular work or not.

You can replace 0's and 1's with words tf-idf value for better results.

You can also consult this for neural network approach for same classification: 
https://github.com/Parassharmaa/neural-network-ppt
